package com.yyq.manager.vo;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Model class of dept.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Dept implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 部门编号. */
	private Integer deptno;

	/** 部门名称. */
	private String dname;

	/** 部门位置. */
	private String loc;

	/** The set of emp. */
	private Set<Emp> empSet;

	/**
	 * Constructor.
	 */
	public Dept() {
		this.empSet = new HashSet<Emp>();
	}

	/**
	 * Set the 部门编号.
	 * 
	 * @param deptno
	 *            部门编号
	 */
	public void setDeptno(Integer deptno) {
		this.deptno = deptno;
	}

	/**
	 * Get the 部门编号.
	 * 
	 * @return 部门编号
	 */
	public Integer getDeptno() {
		return this.deptno;
	}

	/**
	 * Set the 部门名称.
	 * 
	 * @param dname
	 *            部门名称
	 */
	public void setDname(String dname) {
		this.dname = dname;
	}

	/**
	 * Get the 部门名称.
	 * 
	 * @return 部门名称
	 */
	public String getDname() {
		return this.dname;
	}

	/**
	 * Set the 部门位置.
	 * 
	 * @param loc
	 *            部门位置
	 */
	public void setLoc(String loc) {
		this.loc = loc;
	}

	/**
	 * Get the 部门位置.
	 * 
	 * @return 部门位置
	 */
	public String getLoc() {
		return this.loc;
	}

	/**
	 * Set the set of the emp.
	 * 
	 * @param empSet
	 *            The set of emp
	 */
	public void setEmpSet(Set<Emp> empSet) {
		this.empSet = empSet;
	}

	/**
	 * Add the emp.
	 * 
	 * @param emp
	 *            emp
	 */
	public void addEmp(Emp emp) {
		this.empSet.add(emp);
	}

	/**
	 * Get the set of the emp.
	 * 
	 * @return The set of emp
	 */
	public Set<Emp> getEmpSet() {
		return this.empSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((deptno == null) ? 0 : deptno.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Dept other = (Dept) obj;
		if (deptno == null) {
			if (other.deptno != null) {
				return false;
			}
		} else if (!deptno.equals(other.deptno)) {
			return false;
		}
		return true;
	}

	@Override
	public String toString() {
	    StringBuffer buff = new StringBuffer();
	    buff.append(this.getDeptno() + ", " + this.getDname());
	    return new String(buff);
	}
}
