package com.yyq.manager.vo;

import java.io.Serializable;
import java.util.Date;

/**
 * Model class of emp.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Emp implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 雇员编号. */
	private Integer empno;

	/** 雇员姓名. */
	private String ename;

	/** 雇员工作. */
	private String job;

	/** 雇佣日期. */
	private Date hiredate;

	/** 基本工资. */
	private Float sal;

	/** 奖金. */
	private Float comm;

	/** 雇员对应的领导编号. */
	private Integer mgr;

	/** dept. */
	private Dept dept;

	/** 保存雇员的照片路径. */
	private String photo;

	/**
	 * Constructor.
	 */
	public Emp() {
	}

	/**
	 * Set the 雇员编号.
	 * 
	 * @param empno
	 *            雇员编号
	 */
	public void setEmpno(Integer empno) {
		this.empno = empno;
	}

	/**
	 * Get the 雇员编号.
	 * 
	 * @return 雇员编号
	 */
	public Integer getEmpno() {
		return this.empno;
	}

	/**
	 * Set the 雇员姓名.
	 * 
	 * @param ename
	 *            雇员姓名
	 */
	public void setEname(String ename) {
		this.ename = ename;
	}

	/**
	 * Get the 雇员姓名.
	 * 
	 * @return 雇员姓名
	 */
	public String getEname() {
		return this.ename;
	}

	/**
	 * Set the 雇员工作.
	 * 
	 * @param job
	 *            雇员工作
	 */
	public void setJob(String job) {
		this.job = job;
	}

	/**
	 * Get the 雇员工作.
	 * 
	 * @return 雇员工作
	 */
	public String getJob() {
		return this.job;
	}

	/**
	 * Set the 雇佣日期.
	 * 
	 * @param hiredate
	 *            雇佣日期
	 */
	public void setHiredate(Date hiredate) {
		this.hiredate = hiredate;
	}

	/**
	 * Get the 雇佣日期.
	 * 
	 * @return 雇佣日期
	 */
	public Date getHiredate() {
		return this.hiredate;
	}

	/**
	 * Set the 基本工资.
	 * 
	 * @param sal
	 *            基本工资
	 */
	public void setSal(Float sal) {
		this.sal = sal;
	}

	/**
	 * Get the 基本工资.
	 * 
	 * @return 基本工资
	 */
	public Float getSal() {
		return this.sal;
	}

	/**
	 * Set the 奖金.
	 * 
	 * @param comm
	 *            奖金
	 */
	public void setComm(Float comm) {
		this.comm = comm;
	}

	/**
	 * Get the 奖金.
	 * 
	 * @return 奖金
	 */
	public Float getComm() {
		return this.comm;
	}

	/**
	 * Set the 雇员对应的领导编号.
	 * 
	 * @param mgr
	 *            雇员对应的领导编号
	 */
	public void setMgr(Integer mgr) {
		this.mgr = mgr;
	}

	/**
	 * Get the 雇员对应的领导编号.
	 * 
	 * @return 雇员对应的领导编号
	 */
	public Integer getMgr() {
		return this.mgr;
	}

	/**
	 * Set the dept.
	 * 
	 * @param dept
	 *            dept
	 */
	public void setDept(Dept dept) {
		this.dept = dept;
	}

	/**
	 * Get the dept.
	 * 
	 * @return dept
	 */
	public Dept getDept() {
		return this.dept;
	}

	/**
	 * Set the 保存雇员的照片路径.
	 * 
	 * @param photo
	 *            保存雇员的照片路径
	 */
	public void setPhoto(String photo) {
		this.photo = photo;
	}

	/**
	 * Get the 保存雇员的照片路径.
	 * 
	 * @return 保存雇员的照片路径
	 */
	public String getPhoto() {
		return this.photo;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((empno == null) ? 0 : empno.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Emp other = (Emp) obj;
		if (empno == null) {
			if (other.empno != null) {
				return false;
			}
		} else if (!empno.equals(other.empno)) {
			return false;
		}
		return true;
	}

}
